apiVersion: "recommender.com/v1"
kind: "KruizePerformanceProfile"
metadata:
  name: "default-openshift"
profile_version: 1.0
k8s_type: openshift

slo:
  slo_class: "resource_usage"
  direction: "minimize"

  # Refer to src/.../performanceProfiles/PerformanceProfileInterface/DefaultImpl.java
  objective_function:
    function_type: expression
    expression: "(80*min(memoryRSS))/(85*avg(cpuRequest))"

  function_variables:
  # CPU Request
  # Show cpu requests in cores for a container in a deployment
  - name: cpuRequest
    datasource: prometheus
    value_type: "double"
    kubernetes_object: "container"

    aggregation_functions:
    - function: 'avg'
      query: 'avg(kube_pod_container_resource_requests{pod=~"$DEPLOYMENT_NAME$-[^-]*-[^-]*$", container="$CONTAINER_NAME$", namespace="$NAMESPACE", resource="cpu", unit="core"})'

  # 2.4 Memory RSS
  - name: memoryRSS
    datasource: prometheus
    value_type: "double"
    kubernetes_object: "container"

    aggregation_functions:
    # Approx minimum memory RSS per container in a deployment
    - function: min
      query: 'min(min_over_time(container_memory_rss{pod=~"$DEPLOYMENT_NAME$-[^-]*-[^-]*$", namespace=$NAMESPACE$, container="$CONTAINER_NAME$"}[15m]))'
