apiVersion: apiextensions.k8s.io/v1beta1
kind: "CustomResourceDefinition"
metadata:
 #name must match the spec fields below, and be in the form: <plural>.<group>
 name: autotunes.recommender.com
spec:
 # group name to use for REST API: /apis/<group>/<version>
 group: "recommender.com"
 names: 
  plural: autotunes
  singular: autotune
  #types can be identified with this tag
  kind: Autotune 
 scope: Namespaced
 version: v1beta1
 validation: 
  openAPIV3Schema:
   type: object
   properties:
    apiVersion:
      description: 'APIVersion defines the versioned schema of this representation
        of an object. Servers should convert recognized schemas to the latest
        internal value, and may reject unrecognized values. More info: https://git.k8s.io/
        community/contributors/devel/sig-architecture/api-conventions.md#resources'
      type: string
    kind:
      description: 'Kind is a string value representing the REST resource this
           object represents. Servers may infer this from the endpoint the client
           submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/
           community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'  
      type: string
    
    spec:
      description: 'Autotune containts specification parameter for the the recommendation'
      properties:
        sla:
          description: 'sla details the objective function that needs to be optimized'
          properties:
            objective_function: 
              description: 'Objective_function can be a simple or a complex regular expression'
              type: string
            direction:
              description: 'One of maximize or minimize'
              type: string
            sla_class: 
              description: 'One of throughput, response_time or resource_usage'
              type: string
            function_variables: 
              description: 'describe the complex objective_function variables'
              properties:
                name:
                  description: 'name of the variables used in objective_function'  
                  type: string
                query:
                  description: 'query expression for respective datasource'
                  type: string
                datasource:
                  description: 'name of the monitoring tool like prometheus'  
                  type: string
                value_type:
                  description: 'value of the holding objective_function calculation'
                  type: string  
              required:
              - name
              - query
              - value_type    
          required:
          - objective_function
          - direction
          - function_variables
          
        mode:
          description: 'Specify whether to try, show or apply the recommendation'
          type: string 
          required:
          - type
        
        selector:
          description: ' test'
          properties:
            matchLabel:
              description: 'match lable is may be the name of the applications where  
                            recommendation system apply' 
              type: string
            matchLabelValue:
              description: 'match lable value'
              type: string 
            matchRoute:
              description: 'test'
              type: string
            matchURI:
              description: 'test'
              type: string
            matchService:
              description: 'test'
              type: string
        datasource:
          description: 'name of the applicaton which is going to monitor the cluster and
                        provide the data e.g prometheus etc'
          properties:
            name:
              description: 'name of the monitoring agent alias w.r.t autotune'
              type: string
            value:
              description: ' actual name of the monitoring agent software'
              type: string
          required:
          - type
          - value
