apiVersion: apps/v1
kind: Deployment
metadata:
  name: autotune
  labels:
    app: autotune
  namespace: monitoring
spec:
  replicas: 1
  selector:
      matchLabels:
        name: autotune
  template:
    metadata:
      labels:
        app: autotune
        name: autotune
        operatorframework.io/os.linux: supported
    spec:
      containers:
      - name: autotune
        image: "quay.io/khansaad/autotune_operator:0.0.8_mvp"  # will be updated later
        imagePullPolicy: Always
        env:
          - name: CLUSTER_TYPE
            value: "kubernetes"
          - name: K8S_TYPE
            value: "minikube"
          - name: AUTH_TYPE
            value: ""
          - name: AUTH_TOKEN
            value: ""
          - name: MONITORING_AGENT
            value: "prometheus"
          - name: MONITORING_SERVICE
            value: "prometheus-k8s"
          - name: MONITORING_AGENT_ENDPOINT
            value: "prometheus-k8s"
          - name: LOGGING_LEVEL
            value: "info"
          - name: ROOT_LOGGING_LEVEL
            value: "info"
        ports:
         - name: autotune-port
           containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: autotune
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
  labels:
    app: autotune
spec:
  type: NodePort
  selector:
    app: autotune
  ports:
  - name: autotune-port
    port: 8080
    targetPort: 8080
